package exception;

public class Throws2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		try 
		{
			ThrowandThrows tt =new ThrowandThrows();
			tt.m1();
		}
		
	   catch(ArithmeticException e)
		{
		
	    	System.out.println("Enter valid number");
		
	    
	    
	}

}
}